CREATE DATABASE replica
    USER SYS IDENTIFIED BY sys_password   
    USER SYSTEM IDENTIFIED BY system_password
    LOGFILE GROUP 1 ('/u01/prd21/logs/redo01a.log') SIZE 10M,
        GROUP 2 ('/u01/prd21/logs/redo02a.log') SIZE 10M,
        GROUP 3 ('/u01/prd21/logs/redo03a.log') SIZE 10M
    MAXLOGFILES 5
    MAXLOGMEMBERS 5
    MAXLOGHISTORY 10
    MAXDATAFILES 50
    CHARACTER SET UTF8
    NATIONAL CHARACTER SET UTF8
    EXTENT MANAGEMENT LOCAL
    DATAFILE '/u01/prd21/replica/node03/amera75.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
    SYSAUX DATAFILE '/u01/prd21/replica/node03/qac66.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
    DEFAULT TABLESPACE users
        DATAFILE '/u01/prd21/replica/node01/irejese704.dbf'
        SIZE 50M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
    DEFAULT TEMPORARY TABLESPACE temp 
    TEMPFILE '/u01/prd21/replica/temp01.dbf' SIZE 100M REUSE
    UNDO TABLESPACE undotbs1
    DATAFILE '/u01/prd21/replica/undotbs01.dbf' SIZE 100M REUSE 
    AUTOEXTEND ON MAXSIZE UNLIMITED;